spring.application.name=AdriftShip

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/shipDocs
springdoc.api-docs.path=/jsonShipDocs

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

spring.jmx.enabled=false
management.endpoints.jmx.exposure.exclude=*

meli.openapi.dev-url=http://localhost:8080
